### ISSUE TITLE
[IpvanishError] There is no available server

### ISSUE THREAD

**Issue by FriztLang** [Galiley/ipvanish#1]
The program systematically answers me: [IpvanishError] There is no available server. I tried for different countries, and for all countries but a country. Authentification asks for the credentials on IPVanish, but nothing happens once given.

**Comment by Galiley** [comment]
Could you run "sudo ipvanish sync" and then retry?

**Comment by FriztLang** [comment]
>> "sudo ipvanish sync"
[IpvanishError] Failed to update vpn config
>> sudo ipvanish connect
[IpvanishError] There is no available server

Looks like an update is not possible.

**Comment by Galiley** [comment]
@FriztLang I've updated the config.zip URL path and tested the download. However, i can't test the auth and connect command since i've switched to ProtonVPN last year.

**Comment by FriztLang** [comment]
>> sudo ipvanish sync
Ipvanish ovpns files downloaded
2084 servers available

where 2084 corresponds to the number of servers available on IPVanish. so this is an improvement.

then i tried these two commands:
>> ipvanish connect
[IpvanishError] There is no available server
>> sudo ipvanish connect
Retrieving vpn data  [####################################]  100%
Connecting to [Warsaw, Poland, Europe] waw-a07.ipvanish.com (inf ms, 4 %) ...
sudo: openvpn: command not found

I verified the installation of openvpn on my computer. openvpn is installed, and is correctly accessible, but not with the CLI since the command is not working. I then added this line to the .zshrv file (found in a YouTube video):

export PATH="/usr/local/Cellar/openvpn/2.5.0/sbin/:$PATH"

but it is still not working. I still need to check if there is a trouble with my installation. help would be welcome!

**Comment by Galiley** [comment]
Do you have an update on your issue?
Could you try to run on your shell `sudo openvpn` just to see if openvpn is installed and in the PATH?

**Comment by FriztLang** [comment]
I had to find time to fix the error of installation of openvpn on my computer. This command line finally got me running openvpn using the mac terminal: `export PATH=$(brew --prefix openvpn)/sbin:$PATH`

(found on this site : https://apple.stackexchange.com/questions/203115/installed-openvpn-with-brew-but-it-doesnt-appear-to-be-installed-correctly)

`sudo openvpn` is now working and it was indeed a PATH problem. As a result, the program works too. Thank you!

**Comment by FriztLang** [comment]
Thank you. I answered to you on the github issue. I am new at using computer forums. I hope that my interventions are clear enough. 
    Le samedi 23 juillet 2022 à 20:44:29 UTC+2, Galiley ***@***.***> a écrit :  
 
 


Could you run "sudo ipvanish sync" and then retry?

**Comment by FriztLang** [comment]
Thanks for getting back to me to check on my progress. As I was with my family the last few days, I had to find time to figure out the solution. It was indeed a PATH problem, and I explained on the github issue how I solved it. The github program works fine from what I could test. Now I have to see if I can simply program a python script that will allow me to connect and disconnect directly without going through the terminal.
Thanks again for your reactivity and your work.
Sincerely, Matthieu



    Le vendredi 29 juillet 2022 à 22:56:56 UTC+2, Galiley ***@***.***> a écrit :  
 
 


Do you have an update on your issue?
Could you try to run on your shell sudo openvpn just to see if openvpn is installed and in the PATH?
